@API_HostAddress = http://localhost:5000/api



# Login
# @name postLogin
POST {{API_HostAddress}}/account
Content-Type: application/json; charset=utf-8

{
  "email": "tom@test.com",
  "password": "Pa$$w0rd"
}

###
@token = {{postLogin.response.body.token}}


# Get account info
GET {{API_HostAddress}}/account
Content-Type: application/json; charset=utf-8
Authorization: Bearer {{token}}

###

# Create an Activity
POST {{API_HostAddress}}/activities
Content-Type: application/json; charset=utf-8
Authorization: Bearer {{token}}

{
  "id": "{{$guid}}",
  "title": "Test Create Activity",
  "date": "{{$datetime iso8601}}",
  "description": "Description of the test event - bob",
  "category": "Culture",
  "city": "London",
  "venue": "Tower of London"
}
###

# Edit an activity
PUT {{API_HostAddress}}/activities/028db0f3-8dfb-47d0-a1bb-1df46134644a
Content-Type: application/json; charset=utf-8
Authorization: Bearer {{token}}

{
  "title": "Future Activity 81",
  "date": "2025-01-19T20:38:52.6820048",
  "description": "Activity 8 months in future",
  "category": "drinks",
  "city": "London",
  "venue": "Pub",
  "hostUsername": "tom"  
}
###



# Get Activity details
GET {{API_HostAddress}}/activities/028db0f3-8dfb-47d0-a1bb-1df46134644a
Accept: application/json
Authorization: Bearer {{token}}

###

# Get Activity list
GET {{API_HostAddress}}/activities/
Accept: application/json
Origin: http://localhost:3000
Authorization: Bearer {{token}}
###

# Attend to an event
POST {{API_HostAddress}}/activities/8d64d7a3-5aa8-4350-a6de-1ae2c9b2aaff/attend
Accept: application/json
Origin: http://localhost:3000
Authorization: Bearer {{token}}
###
