@API_HostAddress = http://localhost:5000/api

GET {{API_HostAddress}}/activities/
Accept: application/json
Origin: http://localhost:3000

###


GET {{API_HostAddress}}/activities/342c4df2-0550-4dc1-83a2-29d1107ac119
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImJvYiIsIm5hbWVpZCI6IjllNjQ4MTI5LTk4N2QtNDYxOC04NjZkLTcxMGQyZjY5OGY4NCIsImVtYWlsIjoiYm9iQHRlc3QuY29tIiwibmJmIjoxNzE1NDIxMTg5LCJleHAiOjE3MTYwMjU5ODksImlhdCI6MTcxNTQyMTE4OX0.9EuImc5zbCD9C-rkrhIllSoDVw2L3WAwh8aT9Y7TIMppipe21Yd5p77tbO1frXgN85jxOiHIwicaLfOuFdeCyw

###

POST {{API_HostAddress}}/activities
Content-Type: application/json; charset=utf-8

{
  "id": "{{$guid}}",
  "title": "Test Create Activity",
  "date": "{{$datetime iso8601}}",
  "description": "Description of the test event",
  "category": "Culture",
  "city": "London",
  "venue": "Tower of London"
}
###


POST {{API_HostAddress}}/activities
Content-Type: application/json; charset=utf-8

{
}
###



PUT {{API_HostAddress}}/activities/7268fe61-418b-47ac-ae83-64597c1d90a7
Content-Type: application/json; charset=utf-8

{
  "title": "Test Create Activity updated 2",
  "date": "2024-04-28T20:54:25.127",
  "description": "Description of the test event updated 2",
  "category": "Culture",
  "city": "London",
  "venue": "Tower of London 3"
}
###

DELETE  {{API_HostAddress}}/activities/637101df-82fb-432e-9263-76b21bc41dda
Accept: application/json

###