@API_HostAddress = http://localhost:5000/api

GET {{API_HostAddress}}/activities/
Accept: application/json
Origin: http://localhost:3000

###


GET {{API_HostAddress}}/activities/637101df-82fb-432e-9263-76b21bc41dda
Accept: application/json

###

POST {{API_HostAddress}}/activities
Content-Type: application/json; charset=utf-8

{
  "id": "{{$guid}}",
  "title": "Test Create Activity",
  "date": "{{$datetime iso8601}}",
  "description": "Description of the test event",
  "category": "Culture",
  "city": "London",
  "venue": "Tower of London"
}
###


POST {{API_HostAddress}}/activities
Content-Type: application/json; charset=utf-8

{
}
###



PUT {{API_HostAddress}}/activities/7268fe61-418b-47ac-ae83-64597c1d90a7
Content-Type: application/json; charset=utf-8

{
  "title": "Test Create Activity updated 2",
  "date": "2024-04-28T20:54:25.127",
  "description": "Description of the test event updated 2",
  "category": "Culture",
  "city": "London",
  "venue": "Tower of London 3"
}
###

DELETE  {{API_HostAddress}}/activities/637101df-82fb-432e-9263-76b21bc41dda
Accept: application/json

###