@API_HostAddress = http://localhost:5000/api

# Login
# @name postLogin
POST {{API_HostAddress}}/account
Content-Type: application/json; charset=utf-8

{
  "email": "bob@test.com",
  "password": "Pa$$w0rd"
}

###
@token = {{postLogin.response.body.token}}


# Get profile
GET {{API_HostAddress}}/profiles/bob
Content-Type: application/json; charset=utf-8
Authorization: Bearer {{token}}

###
